// preact/src/Card.jsx
import { useState } from "react";

const Card = ({ source, alt }) => {
  const [error, setError] = useState(false);

  if (error) {
    return null;
  }

  return (
    <img
      src={source}
      alt={alt}
      onError={() => {
        setError(true);
      }}
    />
  );
};

export default Card;

// vue/src/components/Card.vue
<script setup>
import { ref } from 'vue';

  const props = defineProps({
    source: {
      type: String,
      required: true
    },
    alt: {
      type: String,
      required: true
    }
  });
  
  const error = ref(false);
</script>

<template>
  <img v-if="!error" :src="source" :alt="alt" v-on:error="() => error = true" />
</template>
