// qwik/src/app.jsx
import { Card } from "@/card";
import { loadPokemonByType } from "@/helpers";
import { component$, useSignal, useTask$ } from "@builder.io/qwik";

const POKEMON_TYPES = {
  Colorless: "⚪️",
  Darkness: "🌑",
  Dragon: "🐉",
  Fairy: "🧚",
  Fighting: "🥊",
  Fire: "🔥",
  Grass: "🌿",
  Lightning: "⚡️",
  Metal: "⚙️",
  Psychic: "🔮",
  Water: "💧",
};

export const App = component$(() => {
  const cards = useSignal([]);
  const filter = useSignal(null);
  const loading = useSignal(false);

  useTask$(({ track }) => {
    const value = track(() => filter.value);

    if (value) {
      loading.value = true;
      loadPokemonByType(value)
        .then((response) => {
          cards.value = response;
          loading.value = false;
        })
        .catch((err) => {
          console.error(`Error loading Pokémon of type ${value}:`, err);
          cards.value = [];
          loading.value = false;
        })
        .finally(() => {
          loading.value = false;
        });
    } else {
      cards.value = [];
      loading.value = false;
    }
  });

  return (
    <div id="main">
      <header>
        <h1>Poké TCG Cards (Qwik)</h1>
      </header>
      <section id="content">
        <aside id="menu">
          {Object.entries(POKEMON_TYPES).map(([type, emoji], k) => {
            return (
              <button
                key={k}
                onClick$={() => {
                  if (filter === type) {
                    filter.value = "";
                  } else {
                    filter.value = type;
                  }
                }}
              >
                {emoji} {type}
              </button>
            );
          })}
        </aside>
        <main>
          <h3 id="filter-name">
            {filter.value ? `Filter: ${filter.value}` : "No filter applied"}
          </h3>

          {loading.value && <span id="loader" className="loading" />}

          <div id="stage">
            {cards.value?.length
              ? cards.value.map((card, c) => {
                  if (!card.image) {
                    return null;
                  }

                  return (
                    <Card
                      key={c}
                      source={`${card.image}/low.png`}
                      alt={card.name}
                    />
                  );
                })
              : "No cards."}
          </div>
        </main>
      </section>
      <footer>
        <p>&copy;2025 Kickops</p>
      </footer>
    </div>
  );
});

// react/src/App.jsx
import { useEffect, useState } from "react";
import { loadPokemonByType } from "@/helpers";
import Button from "@/Button";
import Card from "@/Card";

const POKEMON_TYPES = {
  Colorless: "⚪️",
  Darkness: "🌑",
  Dragon: "🐉",
  Fairy: "🧚",
  Fighting: "🥊",
  Fire: "🔥",
  Grass: "🌿",
  Lightning: "⚡️",
  Metal: "⚙️",
  Psychic: "🔮",
  Water: "💧",
};

const App = () => {
  const [data, setData] = useState([]);
  const [filter, setFilter] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (filter) {
      setLoading(true);
      setData([]);
      loadPokemonByType(filter).then((response) => {
        setData(response);
        setLoading(false);
      });
    } else {
      setData([]);
      setLoading(false);
    }
  }, [filter]);

  return (
    <div id="main">
      <header>
        <h1>Poké TCG Cards (React)</h1>
      </header>
      <section id="content">
        <aside id="menu">
          {Object.entries(POKEMON_TYPES).map(([type, emoji], k) => {
            return (
              <Button
                label={type}
                icon={emoji}
                key={k}
                onClick={() => {
                  if (filter === type) {
                    setFilter(null);
                  } else {
                    setFilter(type);
                  }
                }}
              />
            );
          })}
        </aside>
        <main>
          <h3 id="filter-name">
            {filter ? `Filter: ${filter}` : "No filter applied"}
          </h3>

          {loading && <span id="loader" className="loading" />}

          <div id="stage">
            {data?.length > 0
              ? data?.map((card) => {
                  return (
                    <Card key={card.id} source={`${card.image}/low.png`} alt={card.name} />
                  );
                })
              : "No cards."}
          </div>
        </main>
      </section>
      <footer>
        <p>&copy;2025 Kickops</p>
      </footer>
    </div>
  );
};

export default App;
