// solid/src/Card.jsx
import { createSignal } from "solid-js";

const Card = ({
  source, 
  alt
}) => {
  const [error, setError] = createSignal(false);

  if (error()) return null;

  return (
    <img
      src={source}
      alt={alt}
      onError={(e) => {
        console.error(e);
        setError(true);
      }}
    />
  )
};

export default Card;

// preact/src/Card.jsx
import { useState } from "react";

const Card = ({ source, alt }) => {
  const [error, setError] = useState(false);

  if (error) {
    return null;
  }

  return (
    <img
      src={source}
      alt={alt}
      onError={() => {
        setError(true);
      }}
    />
  );
};

export default Card;
